2024-12-08T15:39:55.622034+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T15:39:55.623592+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: 
2024-12-08T15:39:55.623729+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v5.2.0/libpod/_ping": dial unix /var/folders/pz/0x5jy9vx3wb7l6mxn0sw_x7r0000gn/T/storage-run-501/podman/podman.sock: connect: no such file or directory

2024-12-08T15:39:56.266089+00:00 ERROR 'ansible_navigator.image_manager.puller._log_message' Execution environment pull failed
2024-12-08T15:39:56.936114+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'c3c8377e-1652-47a2-829a-a306fadf78bf', 'counter': 1, 'stdout': 'Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM', 'start_line': 0, 'end_line': 1, 'runner_ident': '030049b2-9690-47da-a2a7-7d8ac399c8d1', 'created': '2024-12-08T15:39:56.934564+00:00'}
2024-12-08T15:39:56.936242+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'c58e81a2-5f6a-42dd-8475-3c10c96f31ba', 'counter': 2, 'stdout': 'Error: unable to connect to Podman socket: Get "http://d/v5.2.0/libpod/_ping": dial unix /var/folders/pz/0x5jy9vx3wb7l6mxn0sw_x7r0000gn/T/storage-run-501/podman/podman.sock: connect: no such file or directory', 'start_line': 1, 'end_line': 2, 'runner_ident': '030049b2-9690-47da-a2a7-7d8ac399c8d1', 'created': '2024-12-08T15:39:56.934752+00:00'}
2024-12-08T15:39:57.045903+00:00 ERROR 'ansible_navigator.actions.run_playbook.write_artifact' Saving the artifact file failed, resulted in the following error: f[Errno 30] Read-only file system: '/test_localhost-artifact-2024-12-08T15:39:57.044986+00:00.json'
2024-12-08T15:40:48.038967+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T15:40:48.039532+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: 
2024-12-08T15:40:48.039583+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v5.2.0/libpod/_ping": dial unix /var/folders/pz/0x5jy9vx3wb7l6mxn0sw_x7r0000gn/T/storage-run-501/podman/podman.sock: connect: no such file or directory

2024-12-08T15:40:48.673310+00:00 ERROR 'ansible_navigator.image_manager.puller._log_message' Execution environment pull failed
2024-12-08T15:40:49.348120+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '5d542b84-45c8-4e3c-8bc8-332d3b511a95', 'counter': 1, 'stdout': 'Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM', 'start_line': 0, 'end_line': 1, 'runner_ident': 'cfaf8e4d-8078-4068-95e3-c6fcb627ecae', 'created': '2024-12-08T15:40:49.341622+00:00'}
2024-12-08T15:40:49.348282+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'c0acd5ec-2988-44fa-96dc-755d091940e8', 'counter': 2, 'stdout': 'Error: unable to connect to Podman socket: Get "http://d/v5.2.0/libpod/_ping": dial unix /var/folders/pz/0x5jy9vx3wb7l6mxn0sw_x7r0000gn/T/storage-run-501/podman/podman.sock: connect: no such file or directory', 'start_line': 1, 'end_line': 2, 'runner_ident': 'cfaf8e4d-8078-4068-95e3-c6fcb627ecae', 'created': '2024-12-08T15:40:49.341836+00:00'}
2024-12-08T15:40:49.460414+00:00 ERROR 'ansible_navigator.actions.run_playbook.write_artifact' Saving the artifact file failed, resulted in the following error: f[Errno 30] Read-only file system: '/test_localhost-artifact-2024-12-08T15:40:49.459581+00:00.json'
2024-12-08T15:41:14.853662+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T15:41:14.854301+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: 
2024-12-08T15:41:14.854351+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v5.2.0/libpod/_ping": dial unix /var/folders/pz/0x5jy9vx3wb7l6mxn0sw_x7r0000gn/T/storage-run-501/podman/podman.sock: connect: no such file or directory

2024-12-08T15:41:15.485412+00:00 ERROR 'ansible_navigator.image_manager.puller._log_message' Execution environment pull failed
2024-12-08T15:41:16.153065+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '0f82b8eb-67f1-43a1-b264-889d77caf90e', 'counter': 1, 'stdout': 'Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM', 'start_line': 0, 'end_line': 1, 'runner_ident': '7d7b78e8-49a1-4ab5-a524-dfc4ccc8d3ef', 'created': '2024-12-08T15:41:16.151582+00:00'}
2024-12-08T15:41:16.153413+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '73bbea2c-0ac9-4d60-8168-8c0dc2f62ce9', 'counter': 2, 'stdout': 'Error: unable to connect to Podman socket: Get "http://d/v5.2.0/libpod/_ping": dial unix /var/folders/pz/0x5jy9vx3wb7l6mxn0sw_x7r0000gn/T/storage-run-501/podman/podman.sock: connect: no such file or directory', 'start_line': 1, 'end_line': 2, 'runner_ident': '7d7b78e8-49a1-4ab5-a524-dfc4ccc8d3ef', 'created': '2024-12-08T15:41:16.151949+00:00'}
2024-12-08T15:41:16.262506+00:00 ERROR 'ansible_navigator.actions.run_playbook.write_artifact' Saving the artifact file failed, resulted in the following error: f[Errno 30] Read-only file system: '/test_localhost-artifact-2024-12-08T15:41:16.260839+00:00.json'
2024-12-08T16:31:26.667344+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T16:31:26.668019+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: []

2024-12-08T16:31:26.668064+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Error: unable to inspect "postgresql_ee:latest": failed to find image postgresql_ee:latest: postgresql_ee:latest: image not known

2024-12-08T16:31:32.213431+00:00 ERROR 'ansible_navigator.image_manager.puller._log_message' Execution environment pull failed
2024-12-08T16:31:39.300916+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '7059cff1-f2a0-4705-81a2-1f8130597fcd', 'counter': 1, 'stdout': 'Error: initializing source docker://postgresql_ee:latest: reading manifest latest in docker.io/library/postgresql_ee: requested access to the resource is denied', 'start_line': 0, 'end_line': 1, 'runner_ident': '063ffd01-395e-494a-bbd8-b3c602b45863', 'created': '2024-12-08T16:31:39.291796+00:00'}
2024-12-08T16:31:39.399700+00:00 ERROR 'ansible_navigator.actions.run_playbook.write_artifact' Saving the artifact file failed, resulted in the following error: f[Errno 30] Read-only file system: '/test_localhost-artifact-2024-12-08T16:31:39.398783+00:00.json'
2024-12-08T16:31:46.636542+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T16:31:46.637035+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: []

2024-12-08T16:31:46.637072+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Error: unable to inspect "postgresql_ee:latest": failed to find image postgresql_ee:latest: postgresql_ee:latest: image not known

2024-12-08T16:31:52.255637+00:00 ERROR 'ansible_navigator.image_manager.puller._log_message' Execution environment pull failed
2024-12-08T16:31:58.009482+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'c2cf10b1-cd6f-4874-b180-690d5b6ce606', 'counter': 1, 'stdout': 'Error: initializing source docker://postgresql_ee:latest: reading manifest latest in docker.io/library/postgresql_ee: requested access to the resource is denied', 'start_line': 0, 'end_line': 1, 'runner_ident': '5b39517b-56a3-423f-ab2d-939b234a7ea1', 'created': '2024-12-08T16:31:57.997814+00:00'}
2024-12-08T16:31:58.106963+00:00 ERROR 'ansible_navigator.actions.run_playbook.write_artifact' Saving the artifact file failed, resulted in the following error: f[Errno 30] Read-only file system: '/test_localhost-artifact-2024-12-08T16:31:58.105544+00:00.json'
2024-12-08T16:32:50.488454+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T16:32:50.489721+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: []

2024-12-08T16:32:50.489762+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Error: unable to inspect "postgresql_ee:latest": failed to find image postgresql_ee:latest: postgresql_ee:latest: image not known

2024-12-08T16:32:55.284444+00:00 ERROR 'ansible_navigator.image_manager.puller._log_message' Execution environment pull failed
2024-12-08T16:33:01.178433+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '32d04451-6ff1-4df5-82d4-8ff80e8904f0', 'counter': 1, 'stdout': 'Error: initializing source docker://postgresql_ee:latest: reading manifest latest in docker.io/library/postgresql_ee: requested access to the resource is denied', 'start_line': 0, 'end_line': 1, 'runner_ident': 'd776627f-f597-4ae9-91da-bd0d81c6100d', 'created': '2024-12-08T16:33:01.173429+00:00'}
2024-12-08T16:35:38.788141+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T16:35:38.789488+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: []

2024-12-08T16:35:38.789534+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Error: unable to inspect "postgres:latest": failed to find image postgres:latest: postgres:latest: image not known

2024-12-08T16:38:50.962354+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'e974a9ce-4f74-48d2-bdd9-0f80212b2fca', 'counter': 1, 'stdout': '/usr/local/bin/docker-entrypoint.sh: line 351: exec: ansible-playbook: not found', 'start_line': 0, 'end_line': 1, 'runner_ident': 'f81c3744-c94a-44ca-8c09-6b94a3a59198', 'created': '2024-12-08T16:38:50.955657+00:00'}
2024-12-08T16:42:54.237504+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T16:42:54.238968+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: []

2024-12-08T16:42:54.239011+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Error: unable to inspect "postgresql_ee:latest": failed to find image postgresql_ee:latest: postgresql_ee:latest: image not known

2024-12-08T16:42:59.036860+00:00 ERROR 'ansible_navigator.image_manager.puller._log_message' Execution environment pull failed
2024-12-08T16:43:06.403839+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '8c8874b8-5a8d-4588-9b36-148d11e3db95', 'counter': 1, 'stdout': 'Error: initializing source docker://postgresql_ee:latest: reading manifest latest in docker.io/library/postgresql_ee: requested access to the resource is denied', 'start_line': 0, 'end_line': 1, 'runner_ident': 'e1f3ac81-6995-4222-82ed-de8a835a257f', 'created': '2024-12-08T16:43:06.399683+00:00'}
2024-12-08T16:44:31.243560+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
2024-12-08T16:44:31.244280+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stdout: []

2024-12-08T16:44:31.244321+00:00 WARNING 'ansible_navigator.image_manager.puller._log_message' stderr: Error: unable to inspect "alpine/ansible:latest": failed to find image alpine/ansible:latest: alpine/ansible:latest: image not known

2024-12-08T16:46:42.507978+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '75b43255-d373-44e7-a051-927e2d71955f', 'counter': 1, 'stdout': '[WARNING]: No inventory was parsed, only implicit localhost is available', 'start_line': 0, 'end_line': 1, 'runner_ident': '26dfb2b3-3825-441d-9868-b7543a551803', 'created': '2024-12-08T16:46:42.495868+00:00'}
2024-12-08T16:46:42.509846+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'c57c5741-c329-4438-a6dd-548694a6e8c8', 'counter': 2, 'stdout': '[WARNING]: provided hosts list is empty, only localhost is available. Note that', 'start_line': 1, 'end_line': 2, 'runner_ident': '26dfb2b3-3825-441d-9868-b7543a551803', 'created': '2024-12-08T16:46:42.497047+00:00'}
2024-12-08T16:46:42.509912+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '6c2df56d-eef0-49c3-a4c5-ef753c323fc7', 'counter': 3, 'stdout': "the implicit localhost does not match 'all'", 'start_line': 2, 'end_line': 3, 'runner_ident': '26dfb2b3-3825-441d-9868-b7543a551803', 'created': '2024-12-08T16:46:42.497097+00:00'}
2024-12-08T16:47:42.125674+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '89d729aa-1923-4c5a-830d-c92ae01ff1c2', 'counter': 1, 'stdout': '[WARNING]: No inventory was parsed, only implicit localhost is available', 'start_line': 0, 'end_line': 1, 'runner_ident': 'fb43ccf3-4ac6-4aff-bbca-c4c0b00b6225', 'created': '2024-12-08T16:47:42.124382+00:00'}
2024-12-08T16:47:42.137414+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'a0b29fbc-5916-43b7-824f-a234d3892758', 'counter': 2, 'stdout': '[WARNING]: provided hosts list is empty, only localhost is available. Note that', 'start_line': 1, 'end_line': 2, 'runner_ident': 'fb43ccf3-4ac6-4aff-bbca-c4c0b00b6225', 'created': '2024-12-08T16:47:42.126011+00:00'}
2024-12-08T16:47:42.137487+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'fabc33d5-e05f-452d-9035-0020c8ca5f5d', 'counter': 3, 'stdout': "the implicit localhost does not match 'all'", 'start_line': 2, 'end_line': 3, 'runner_ident': 'fb43ccf3-4ac6-4aff-bbca-c4c0b00b6225', 'created': '2024-12-08T16:47:42.126064+00:00'}
2024-12-08T19:44:05.812497+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'd41ff29f-91e1-4174-b023-3dc03aa0f5f5', 'counter': 1, 'stdout': '[WARNING]: No inventory was parsed, only implicit localhost is available', 'start_line': 0, 'end_line': 1, 'runner_ident': '97c2ff90-1ef9-4f55-bac8-78522be6da43', 'created': '2024-12-08T19:44:05.805220+00:00'}
2024-12-08T19:44:05.812798+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'b77e04a5-1d15-4b8c-94bd-449c1cc5f2ae', 'counter': 2, 'stdout': '[WARNING]: provided hosts list is empty, only localhost is available. Note that', 'start_line': 1, 'end_line': 2, 'runner_ident': '97c2ff90-1ef9-4f55-bac8-78522be6da43', 'created': '2024-12-08T19:44:05.806737+00:00'}
2024-12-08T19:44:05.812849+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '2cb76acd-b580-4404-91ec-d62ae4a6159e', 'counter': 3, 'stdout': "the implicit localhost does not match 'all'", 'start_line': 2, 'end_line': 3, 'runner_ident': '97c2ff90-1ef9-4f55-bac8-78522be6da43', 'created': '2024-12-08T19:44:05.806786+00:00'}
